[package]
name = "wr-stats"
version = "0.3.7"
authors = ["Eivind E. Dahl <eivind.dahl@gmail.com>"]
build = "build.rs"

[dependencies]
csv = "*"
regex = "*"
elma = "*"
web-view = "*"
notify = "*"
serde = "*"
serde_derive = "*"

[target.'cfg(windows)'.build-dependencies]
winres = { git = "https://github.com/mxre/winres" }
