[package]
name = "wr-stats"
version = "0.3.0"
authors = ["Eivind E. Dahl <eivind.dahl@gmail.com>"]

[dependencies]
csv = "*"
regex = "*"
elma = "*"
web-view = { git = "https://github.com/Boscop/web-view", branch = "master" }
notify = "*"
