[package]
name = "wr-stats"
version = "0.2.0"
authors = ["Eivind E. Dahl <eivind.dahl@gmail.com>"]

[dependencies]
csv = "*"
regex = "*"
elma = { git = "https://github.com/hexjelly/elma-rust", branch = "master" }
web-view = { git = "https://github.com/Boscop/web-view", branch = "master" }
notify = "*"